# application.yml

spring:
  application:
    name: auction-backend
  # [Spring Cloud AWS 설정] Parameter Store 연동
  config:
    import: "aws-parameterstore:/auction/prod/"

# --- Production Profile (prod) ---
spring:
  config:
    activate:
      on-profile: prod

  # [데이터베이스 연결 설정]
  datasource:
    url: jdbc:mariadb://auction-db.c5wk2um82f9a.ap-northeast-2.rds.amazonaws.com:3306/auction-db?useSSL=false
    username: admin
    # password는 Parameter Store에서 `db.password`로 자동 주입됨
    password: ${db.password}
    driver-class-name: org.mariadb.jdbc.Driver

  # [JPA 및 Hibernate 설정]
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      # ❌ 절대로 update, create, create-drop 사용 금지
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # [Flyway 설정]
  flyway:
    enabled: true
    baseline-on-migrate: true # 기존 테이블이 있을 경우, 첫 마이그레이션을 베이스라인으로 설정

  # ❌ 파일 업로드는 S3와 같은 외부 스토리지를 사용하도록 변경해야 함
  servlet:
    multipart:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    # GMAIL_USERNAME, GMAIL_APP_PASSWORD는 Parameter Store에서 주입
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080
  error:
    # ❌ 프로덕션에서 스택 트레이스 노출 절대 금지
    include-stacktrace: never
    include-message: always

# JWT, Actuator, 로깅 레벨 등도 프로파일에 맞게 조정해야 함
# 예: logging.level.com.auction=INFO