version: 0.0
os: linux
files:
  # buildspec.yml에서 이름을 변경한 app.jar를 복사합니다.
  - source: build/libs/app.jar
    destination: /home/ubuntu/
  # scripts 폴더 전체를 EC2 서버의 /home/ubuntu/scripts 경로로 복사합니다.
  - source: scripts
    destination: /home/ubuntu/scripts
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  # [수정] BeforeInstall 대신 AfterInstall을 사용합니다.
  # 이 훅은 파일이 EC2에 복사된 '이후'에 실행됩니다.
  AfterInstall:
    - location: scripts/setup_permissions.sh # 새로운 권한 설정 스크립트
      timeout: 300
      runas: root # root 권한으로 파일 소유권 및 권한을 설정합니다.
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
