version: 0.0
os: linux
files:
  # buildspec.yml에서 이름을 변경한 app.jar를 복사합니다.
  - source: build/libs/app.jar
    destination: /home/ubuntu/
  # scripts 폴더 전체를 EC2 서버의 /home/ubuntu/scripts 경로로 복사합니다.
  - source: scripts
    destination: /home/ubuntu/scripts
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
