version: 0.0
os: linux
files:
  - source: build/libs/app.jar
    destination: /home/ubuntu/
  - source: scripts
    destination: /home/ubuntu/scripts
hooks:
  # 새 버전의 애플리케이션 설치 후 실행될 훅들
  AfterInstall:
    - location: scripts/setup_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  # 트래픽을 전환하기 전에 새 버전이 정말 정상인지 검증하는 가장 중요한 단계
  ValidateService:
    - location: scripts/validate_service.sh # 이 스크립트는 직접 만들어야 한다.
      timeout: 60
      runas: ubuntu
# --- 블루/그린 배포를 위한 핵심 설정 ---
loadBalancerInfo:
  targetGroupInfoList:
    # CodeDeploy가 트래픽을 제어할 로드밸런서의 원본 대상 그룹 이름을 명시한다.
    - name: "auction-backend-tg"