version: 0.2

phases:
  install:
    # CodeBuild 환경에서 사용할 Java 버전을 명시적으로 지정하는 것이 좋습니다.
    runtime-versions:
      java: corretto17
    commands:
      # -------------------------------------------------------------------
      # [수정] 가장 먼저 백엔드 디렉터리로 이동해야 합니다.
      # -------------------------------------------------------------------
      - cd auction-backend
      - echo "Entered auction-backend directory. Current path is $(pwd)"

  build:
    commands:
      - echo "Granting execute permission to gradlew"
      - chmod +x ./gradlew
      - echo "Building the Spring Boot application"
      # '-x test' 옵션을 추가하면 빌드 시 테스트를 건너뛰어 시간을 단축할 수 있습니다.
      - ./gradlew build -x test

  post_build:
    commands:
      - echo "Renaming jar file to app.jar"
      - mv build/libs/*.jar build/libs/app.jar

artifacts:
  # 아티팩트의 기준 디렉터리는 리포지토리 루트 기준이므로 'auction-backend'가 맞습니다.
  base-directory: 'auction-backend'
  files:
    # 이제 이름이 변경된 app.jar를 포함시킵니다.
    - 'build/libs/app.jar'
    - 'appspec.yml'
    - 'scripts/**/*'
